env:
  browser: true
  node: true
  es2021: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: script
plugins:
  - react
rules: {}
