version: "3.9"

services:

  bilbomd-redis:
    image: redis
    container_name: bilbomd-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - app-network

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:bilbomd-redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network

  bilbomd-backend:
    container_name: bilbomd-backend
    build:
      context: ./
      dockerfile: ./docker/bilbomd/backend/Dockerfile
    image: bl1231/bilbomd-backend
    deploy:
      resources:
        limits:
          cpus: '12'
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=bilbomd-mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - REDIS_URL=$REDIS_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - "3500:3500"
    volumes:
      - ./:/home/node/app
      - bilbomd:/bilbomd/uploads
      # - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh bilbomd-mongodb:27017 -- /home/node/app/node_modules/.bin/nodemon server

  bilbomd-mongodb:
    image: mongo:6.0.4
    container_name: bilbomd-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:27017"
    volumes:
      - dbdata:/data/mongodb
    networks:
      - app-network
  # bilbomd-worker:
  #   build:
  #     context: ./
  #     dockerfile: docker/bilbomd/worker/Dockerfile
  #   image: bl1231/bilbomd-worker
  #   container_name: bilbomd-worker
  #   restart: unless-stopped
  #   env_file: .env
  #   networks:
  #     - app-network
  #   volumes:
  #     - bilbomd:/bilbomd/uploads

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  cache:
  bilbomd:
