###
GET http://localhost:3502

###
GET http://localhost:3502/nope

###
POST http://localhost:3502/register
content-Type: application/json

{ "user": "sclassen", "email": "scott.classen@gmail.com"}

###
POST http://localhost:3502/register
content-Type: application/json

{ "user": "doodguy123", "email": "sclassen@lbl.gov"}

###
POST http://localhost:3502/register
content-Type: application/json

{ "user": "sclassen", "email": "scott.classen@me.com", "nope": "shouldnotbehere"}

###
POST http://localhost:3502/verify
content-Type: application/json

{ "code": "qKsn4FS6S3hHZOTfcupaAx7gLNmLUMRVYFtj"}


###
POST http://localhost:3502/auth/otp
content-Type: application/json

{ "otp": "Ms5pExCKo4NYrz03GHCfjEKsKLodTPDYPb"}

###
POST http://localhost:3502/magicklink
content-Type: application/json

{ "email": "scott.classen@me.com"}


###
POST http://localhost:3502/verify/resend
content-Type: application/json

{ "email": "scott.classen@me.com"}