name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - 478-test-cicd-bilbomd-backend  # Updated to custom branch for testing

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Configure npm registry
      run: |
        echo "@bl1231:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push bilbomd-backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: bilbomd-backend.dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:bilbomd-backend-latest
        build-args: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }}

    - name: Build and push bilbomd-spin-backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: bilbomd-spin-backend.dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:bilbomd-spin-backend-latest
        build-args: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }}
