name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure npm registry
        run: |
          echo "@bl1231:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci --force

      - name: Build the project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/bilbomd-backend
          tags: |
            type=raw,value=latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate version from tag
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get version from package.json
        id: get_version
        run: echo "BILBOMD_BACKEND_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Get short Git hash
        id: git-info
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push bilbomd-backend Docker image (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bilbomd-backend.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/bilbomd-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USER_ID=${{ vars.USER_ID }}
            GROUP_ID=${{ vars.GROUP_ID }}
            GIT_HASH=${{ env.GIT_HASH }}
            BILBOMD_BACKEND_VERSION=${{ env.BILBOMD_BACKEND_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push bilbomd-backend Docker image (versioned)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bilbomd-backend.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/bilbomd-backend:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USER_ID=${{ vars.USER_ID }}
            GROUP_ID=${{ vars.GROUP_ID }}
            GIT_HASH=${{ env.GIT_HASH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
